#ifndef WRIST_STATES_H
#define WRIST_STATES_H
//#define STATE_OFF 0  // comment out to not redefine
#define STATE_RING_ALL_RAINBOW 1
#define STATE_RING_ALL_PURPLE 2
#define STATE_RING_ALL_RED 3
#define STATE_RING_CHASE4CLK_RAINBOW 4
#define STATE_RING_CHASE4CLK_PURPLE 5
#define STATE_RING_CHASE4CLK_RED 6
#define STATE_RING_CHASE4NCLK_RAINBOW 7
#define STATE_RING_CHASE4NCLK_PURPLE 8
#define STATE_RING_CHASE4NCLK_RED 9
#define STATE_RING_CHASE2CLK_RAINBOW 10
#define STATE_RING_CHASE2CLK_PURPLE 11
#define STATE_RING_CHASE2CLK_RED 12
#define STATE_RING_CHASE2NCLK_RAINBOW 13
#define STATE_RING_CHASE2NCLK_PURPLE 14
#define STATE_RING_CHASE2NCLK_RED 15
#define STATE_RING_CHASE1CLK_RAINBOW 16
#define STATE_RING_CHASE1CLK_PURPLE 17
#define STATE_RING_CHASE1CLK_RED 18
#define STATE_RING_CHASE1NCLK_RAINBOW 19
#define STATE_RING_CHASE1NCLK_PURPLE 20
#define STATE_RING_CHASE1NCLK_RED 21

#define NUM_RING_STATES 22  // Total number of stats
#endif // WRIST_STATES_H
